#!/usr/bin/env python3
"""Emit the fault-injection numbers as LaTeX macros."""
import json
d = json.load(open("../5_derived_results/c6_injection.json"))
faults = {k: v for k, v in d.items() if v["kind"] == "fault"}
healthy = {k: v for k, v in d.items() if v["kind"] == "healthy"}
beh = lambda v: [x for x, y in v["checks"].items() if y is True and x != "T3"]
M = {
 "CSixNFault": len(faults), "CSixNHealthy": len(healthy),
 "CSixCaught": sum(1 for v in faults.values() if beh(v)),
 "CSixMissed": sum(1 for v in faults.values() if not beh(v)),
 "CSixFalseAlarm": sum(1 for v in healthy.values() if beh(v)),
 "CSixTThreeFires": sum(1 for v in d.values() if v["checks"].get("T3") is True),
 "CSixN": len(d),
 "CSixHealthyG": f"{healthy['healthy']['global_last3']:.3f}",
 "CSixHealthyL": f"{healthy['healthy']['local_last3']:.3f}",
 "CSixBufG": f"{faults['buffers not shared']['global_last3']:.3f}",
 "CSixBufL": f"{faults['buffers not shared']['local_last3']:.3f}",
}
with open("./c6_values.tex", "w") as f:
    f.write("% AUTO-GENERATED by figures/c6_values.py\n")
    for k, v in M.items(): f.write(f"\\newcommand{{\\{k}}}{{{v}}}\n")
for k, v in M.items(): print(f"  {k:18s} {v}")
